<script type="text/javascript" src="/public/js/jquery.pager.js" ></script>
<link rel="stylesheet" type="text/css" href="/public/css/Pager.css"/>
<div  class='dialog_style'>
	 <div class='dialog_left'>
		<form class="form" id='goods_edit'>
			<input type='hidden' name='goods_id_edit' value=''>
			<table width='90%;height:auto;'>
				<input type='hidden' name='store_goods_id_edit'  value="">
				<tr>
					<th class='td_left'>商品名称：</th>
					<td>
						<input type="text" name="goods_name_edit" class='goods_name_edit'/>
						<span class='goods_name_edit_error' style='color:red'></span>
					</td>
				</tr>
				
				<tr>
					<th class='td_left'>菜品分类：</th>
					<td class='gcategory_edit_goods'></td>
				</tr>

				<tr>
					 <th class='td_left'>网站分类：</th>
					 <td class='category_edit'>
						
					 </td> 
				</tr>
				 
				<tr>
					<th class='td_left'>价格：</th>
					<td><input type="text" name="price_edit"/></td>
				</tr>

				<tr>
					<th class='td_left'>包装费：</th>
					<td><input type="text" name="packing_fee_edit"/></td>
				</tr>

				<tr>
					<th class='td_left'>有票折扣：</th>
					<td><input type="text" name="receipt_discount_edit"/></td>
				</tr>

				<tr>
					<th class='td_left'>无票折扣：</th>
					<td><input type="text" name="nreceipt_discount_edit"/></td>
				</tr>

				<tr>
					<th class='td_left'>单位：</th>
					<td><input type="text" name="spec_name_edit"/></td>
				</tr>


				<tr>
					<th class='td_left'>上架：</th>
					<td class='if_show'>
						<input type="radio" name="if_show_edit" value='1'/ required>是
						<input type="radio" name="if_show_edit" value='0'/>否
					</td>
				</tr>

				<tr>
					<th class='td_left'>商品描述：</th>
					<td><textarea cols='30' rows='5' name='summary_edit' class='summary_edit'></textarea ></td>
				</tr>
				
				<tr>
					<th class='td_left'>搜索商品图片</th>
					<td><input type='text' name='image_search'>
						<input type='hidden' name='search_image_edit' value=''>
						<a href="javascript:void(0);" class="image_search_five" >搜索</a>
					</td>
				</tr>
				
				<tr>
					<th class='td_left'>商品图片：</th>
					<td><input type='file' name='file_goods_edit'></td>
				</tr>

		  </table>
		  
		  <span class="error_show" style="width:200px;color:red;height:40px;line-height:41px;margin-left:180px"></span>
			
		  <div class="submit" style="width:200px;padding-left:85%;">
					<input type="submit" value="提交" />
		  </div>

		  <div class='goods_edit_error' style='color:red'></div>
			
		  <div id='upload_default_image_edit' style="width:84%;margin:0 auto;margin-top:20px">  <!--默认的上传图片-->
		  </div>

		  <div class="image_xs" style="width:84%;margin:0 auto;margin-top:20px">
				<div class='image_summary_edit' ></div>
				<div class='image_show_edit' ></div>
		  </div>

		</form>
	  </div>
</div>


<script type='text/javascript'>
	$(function(){
		//搜索图片url
		$(".image_search_five").on("click",function(){
	   		PageClick();
	    });
		
		
		//点击图片(搜索)
	    $(document).on("click",'.image_search_show',function(){
	   		var img_value = $(this).attr("value");
			$("input[name='search_image_edit']").val(img_value);
			$(".image_summary_edit").html("");
			$(".image_show_edit").html($(this).html());
			
	   	});
		

	});//声明结束位置



		PageClick = function(pageclickednumber)
	 	{
		 	if(pageclickednumber=='')
		 	{
		 		pageclickednumber='1';
		 	}
	 		var keyword = $("input[name='image_search']").val();
		   		if(keyword.length<1)
		   		{
		   			alert("请输入要查询图片的名字");
		   			return false;
		   		}
	   			$(".image_summary_edit").show();

		   		//搜索图片
		   		$.ajax({
		   			type:'post',
		   			dataType:'json',
		   			data:{"keyword":keyword,"page":pageclickednumber},
		   			url:"/goods/goods/search",
		   			success:function(result)
		   			{
		   				if(result.state!=1)
		   				{
		   					alert(result.message);
		   					return false;
		   				}

		   				var html="";
		   				$.each(result.data,function(key,value){
						
		   					html+= "<div class='image_search_show'  value='"+value['image_url']+"/"+value['image_hash']+".jpg'><image value='"+value['image_id']+"' width='150px'  src='/public/img/store/public/"+value['image_url']+"/"+value['image_hash']+".jpg'></div>";
							
		   				});
		   		
		   				$(".image_show_edit").empty();
		   				$(".image_show_edit").html(html);
		   				$(".image_summary_edit").pager({pagenumber:pageclickednumber,pagecount:result.num,buttonClickCallback: PageClick });
		   				
		   			}
		   		});
   		}
</script>

<script type='text/javascript'>

		//编辑菜品时的名字验证
		  $(document).on("blur",".goods_name_edit",function(){

				var goods_name = $(this).val();

				var  store_id  = $("input[name='store_goods_id_edit']").val();
				
				var goods_id   = $("input[name='goods_id_edit']").val();

				if(goods_id == '')
				{
					return false;
				}
				
				if(goods_name=='')
				{
					return false;
				}

				if(store_id=='')
				{
					return false;
				}
				
				$.post('/store/store/goods_name_edit',{'goods_id':goods_id,'goods_name':goods_name,'store_id':store_id},function(result){
					if(result.state!='1')
					{
						$(".goods_name_edit_error").html(result.message);
					}else
					{
						$(".goods_name_edit_error").html(" ");
					}
				},'json');
			});

		//表单自定义验证有票折扣和无票折扣
		$.validator.addMethod("zhekou_check",function(value,element){
			var score = /0\.[0-9]*[0-9]$/;
			var score_two  = /1.00$/;
			return (score.test(value) || score_two.test(value));
		},"<font color='#E47068'>请输入正确的折扣率(0.00-1.00)</font>");
	
	    //菜品验证和编辑
		$("#goods_edit").validate({
				debug:true,
				rules:{
					goods_name_edit:{required: true,},
					cate_id_edit:{required: true,},
					gcategory_goods_edit:{required: true,},
					price_edit:{required: true,number_check:true,},
					packing_fee_edit:{required: true,number_check:true,},
					receipt_discount_edit:{zhekou_check:true,},
					nreceipt_discount_edit:{zhekou_check:true},
					spec_name_edit:{required:true,},
					if_show_edit:{required:true,},
				},
				messages:{
					goods_name_edit:'请填入菜品名字',
					cate_id_edit:'请选择出餐时间',
					gcategory_goods_edit:'请选择菜品分类',
					spec_name_edit:'请写入单位',
					if_show_edit:'请选择菜品上下架',
				},
				
				errorPlacement: function(error,element)
				{ //指定错误信息位置
					if(element.is(':radio'))
					{ 
						error.appendTo(element.parent()); 
					}else
					{
						error.insertAfter(element); 
					}
				}, 
				
				submitHandler:function(){  
				
						var options = {
							url:'/goods/goods/update',
							type:'post',
							dataType:'json',
							beforeSubmit:function(){
								//取消提交按钮
								var msg = "<td></td>";
									msg +="<td>正在提交请稍后....</td>";	
								$("#goods_edit .submit").html(msg);		
							},
							success:function(result)
							{
								var reset_msg = "<td></td>";
									reset_msg +="<td><input type='submit' value='提交' /></td>";	
								$("#goods_edit .submit").html(reset_msg);
		
								if(result.state!=1)
								{
									$(".goods_edit_error").html(result.message);
									return false;
								}
								

								//修改成功针对店铺下和菜品下展示新的数据

								success(result.data);
								
								alert("修改菜品成功");

								$("#goods_dialog_edit").dialog("close");
					
								
							}
							
						};
						
						$("#goods_edit").ajaxSubmit(options);
						return false;
				},
			
		
		});	
</script>

