{include file="$app_path/application/views/header.phtml"}
<script src="/application/modules/Custom/public/js/order.js"></script>
<link type="text/css" rel="stylesheet" href="/public/css/ui.jqgrid.css">
<link type="text/css" rel="stylesheet" href="/public/css/ui.order.css">
<script type="text/javascript" src="/public/js/grid.locale-cn.js"></script>
<script type="text/javascript" src="/public/js/jquery.jqGrid.min.js"></script>
<?php
var_dump({$partnerList});
?>