<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>客服系统</title>
<link rel="stylesheet" href="/public/css/jquery-ui-1.10.4.css" />
<link rel="stylesheet" href="../public/css/crmbase.css" />
<script src="/public/js/jquery-1.10.2.min.js"></script>
<script src="/public/js/jquery-ui-1.10.4.min.js"></script>
<script src="/public/js/crmbase.js"></script>
<script src="/public/js/socket.io.js"></script>