<meta charset="utf-8">
<style>
	.box_order{
		width:1150px;
		height:220px;
		margin:auto;
		}
	.box_store{
		width:1150px;
		margin:auto;
	}
	.box_goods{
		width:1150px;
		height:80px;
		margin:auto;
	}
</style>
<div style="margin-left:auto;margin-right:auto;background:#EEEEEE;">
<div>
	优惠代码<input type="text"><br/>
</div>
<div class="box_order">				<!-- 订单区域 -->
<table cellpadding="2">
	<tr>
		<td>订单编号:</td>
		<td>{$detail.order_sn}</td>
		<td>订单状态:</td>
		<td>{$detail.status}</td>
		<td>订单日期:</td>
		<td>{$detail.addtime}</td>
		<td>确认日期:</td>
		<td>{$detail.confirm_time}</td>
	</tr>
	<tr>
		<td>支付方式:</td>
		<td>{$detail.payment_name}</td>
		<td>区域:</td>
		<td><select name="" id=""></select></td>
		<td>配送方式:</td>
		<td>??</td>
		<td>要求送达时间:</td>
		<td>{$detail.request_time}</td>
	</tr>
	<tr>
		<td>买家:</td>
		<td>{$detail.buyer_name}</td>
		<td>联系电话:</td>
		<td>13522996744</td>
		<td>送餐地址</td>
		<td>{$detail.address}</td>
	</tr>
	<tr>
		<td>收货人</td>
		<td>{$detail.consignee}</td>
		<td>收货人电话</td>
		<td>{$detail.phone_mob}</td>
		<td>餐厅是否确认</td>
		<td>??</td>
	</tr>
	<tr>
		<td>订单备注:</td>
		<td>??</td>
	</tr>
	<tr>
		<td>客服备注:</td>
		<td><input type="text"><input type="button" value="添加"></td>
		<td>调度备注:</td>
		<td><input type="text"><input type="button" value="添加"></td>
	</tr>
	<tr>
		<tr>
			<td>发票类型</td>
			<td>{$detail.invoice_type}</td>
			<td>发票title</td>
			<td>{$detail.invoice_title}</td>
		</tr>
	</tr>
</table>	
</div>
<div class="box_store">				<!-- 店铺区域 -->
	<table>
		<tr>
			<td>店铺</td>
			<td>{$detail.store_name}</td>
			<td>联系电话</td>
			<td>{$detail.tel}</td>
			<td>合作伙伴</td>
		</tr>
		<tr>
			
		</tr>
	</table>
</div>
<div class="box_goods">				<!-- 菜品区域 -->
	<table border="1" cellspacing="0">
	<section></section>
		<tr>
			<td>菜品</td>
			<td>数量</td>
			<td>单价</td>
			<td>促销价</td>
			<td>规格</td>
			<td>包装费</td>
			<td>描述</td>
			<td>当前折扣</td>
			<td>会员价</td>
			<td>无票折扣</td>
			<td>有票折扣</td>
		</tr>
		{section loop=$detail name=n}
		<tr>
			<td>{$n.goods_name}</td>
			<td>1</td>
			<td>49.00</td>
			<td></td>
			<td>锅</td>
			<td>1.00</td>
			<td></td>
			<td>0.85</td>
			<td>0.00</td>
			<td>0.85</td>
			<td>0.85</td>
		</tr>
		{/section}
	</table>
</div>
<div class="box_order">				<!-- 计算区域 -->
	<input type="button" value="重新计算">
	<table>
		<tr>
			<td>税点：0.0000</td>
			<td快递费(￥)：></td>
			<td>实付金额(￥)：</td>
		</tr>
		<tr>
			<td>餐厅管理费(￥)：</td>
			<td>菜品总额(￥)：(￥)：</td>
			<td>实付金额(￥)：</td>
		</tr>
		<tr>
			<td>采购价(￥)：</td>
			<td>包装费(￥)：</td>
			<td>实收快递费(￥)：</td>
		</tr>
		<tr>
			<td>应付总金额(￥)：</td>
			<td>应收总金额(￥)：</td>
			<td>实付包装费(￥)：</td>
		</tr>
		<tr>
			<td>支付状态(￥)：</td>
			<td>金额调整(￥)：</td>
			<td>原始应收总额(￥)：</td>
		</tr>
	</table>
</div>
<div class="box_order">
	<input type="button" value="上一条">
	<input type="button" value="餐厅确认">
	<input type="button" value="关闭">
	<input type="button" value="下一条">
</div>
</div>