<!doctype html>
<html lang="en">
  <head>
  <meta charset="utf-8">
  <title>百度店铺</title>
  <script src="/public/js/jquery-1.10.2.min.js"></script>
  <script src="/public/js/jquery-ui-1.10.4.min.js"></script>
  <link href="/public/css/jquery-ui-1.10.4.css" rel="stylesheet" type="text/css">
  <script type="text/javascript">
    $(function()
   {
    var c="";
    var f="";
    $('.sxj').click(function()
    {
      //根据button的值来判断上架还是下架
      var    sxj=$(this).val(); //获取点击的上架还是下架
      var    store_id=$(this).find('input').val(); 
      //判断你是否上架还是下架的提示
      if(sxj==1)
        {
          var sm='你确定要上架吗';
        }else if(sxj==2)
        {
          var sm='你确定要下架吗';
        }
      if(confirm(sm)) 
      {
        $.ajax({
          type:'POST',
          url:'chuli',
          dataType:'json',
          data:
          {
            store_id:store_id,
            state:sxj,
          },
          success : function(response, status, xhr)
             {
               c=response.state;
               f=response.false11;
               if(response.state==1)
                  {  
                  $("p"+"."+store_id).html(function(){
                      return "<font color='red'>已上架</font>";
                   });
                  $("font"+"."+store_id).html( function(){ return "下架";});
                  $("#"+store_id).val(function() { return 2;});
                   }else if(response.state==2)
                    {
                    $("p"+"."+store_id).html(function()
                      {
                        return "<font color='blue'>已下架</font>";
                      });
                    $("font"+"."+store_id).html( function(){ return "上架";}); 
                    $("#"+store_id).val(function(){ return 1;});
                    }else if(response.false11==3) 
                      {
                        return false;
                      }
                  }
                  }); 
        } 
      });    
        $(document).ajaxStart(function ()
          {
            $('.loading').dialog(
              {
                width:500,
                height:300,
                title:'正在加载中'
              });
          }).ajaxSuccess(function()
          {
            if(c==1)
            {
              $('.loading').dialog('close');
              alert("已完成上架");
            }else if(c==2)
            {
              $('.loading').dialog('close');
              alert("已完成下架");
            }else if(f==3)
            {
              $('.loading').dialog('close');
              alert("修改失败");
            }
          });
                            
 }); 
   </script>
</head>
  <body>
<h2  style="text-align:center">店铺上下架一览表</h2>
<div class="loading"  style="width:300px;height:100px;display:none;"/>
    <img src="/public/img/ajax-loader.gif"/>
</div>
<div style="text-align:center;margin-bottom:30px">
  <form action="index" method="get">
    店铺名称 <input type="text" name="store_name1" value='{if $store_name1 neq ''}{$store_name1} {/if}' style="margin-left:-20px;width:80px;"/>

   所在区域    <select  name="qy">
                   <option value='{$region_id1}' selected='selected'> {if $region_qyname neq ''} {$region_qyname} {else}全部{/if} </option>
                    {foreach from=$sqlqylist  item=value}
                    <option value='{$value.region_id}'> {$value.region_name}</option> 
                    {/foreach}
                </select>
       &nbsp;上下架状态
         <select name="shangxiajia">
          {if $state eq ''}
           <option  value="" selected='selected' > 全部</option>
           <option value="1" >已上架</option>
           <option  value="2" >已下架</option> 
          {/if}
          {if $state eq "1"}
            <option  value=""> 全部</option>
            <option value="1" selected='selected' >已上架</option>
            <option  value="2" >已下架</option> 
          {/if}
          {if $state eq "2"}
            <option  value=""> 全部</option>
            <option value="1">已上架</option>
            <option  value="2" selected='selected'>已下架</option>
          {/if}
        </select>
 <input type="submit" value="查询"/>
 &nbsp;<a href="{$all}">查看全部</a>
</form>
</div>
  <table  border="1" cellpadding="0" cellspacing="0" align='center' >
    <tr>
      <th style="width:80px;">店铺id</th>
      <th>店铺名字</th>
      <th>所在区域</th>
      <th>美食状态</th>
      <th>百度状态</th>
      <th>操作</th>
    </tr>
    <tr></tr>
{foreach from=$xianlist  item=value}
  {if $value neq ''}
 <tr align='center'>
   <td >{$value.store_id}</td>
   <td >{$value.store_name}</td>
   <td >{$value.region_name}</td>
 <td>
   {if $value.state eq '1'}
     <p class={$value.store_id}>已上架</p>
       {elseif $value.state eq '2'}
     <p  class={$value.store_id}>已下架</p>
  {/if}
 </td>
  <td>
   {if $value.state eq '1'}
     <p class={$value.store_id}>已上架</p>
       {elseif $value.state eq '2'}
     <p  class={$value.store_id}>已下架</p>
  {/if}
 </td>
<td width='20%'>
   {if $value.state eq '2'}
     <button class='sxj'  value='1' id="{$value.store_id}">
        <input type="hidden" value="{$value.store_id}"/>
        <font color='red' class="{$value.store_id}" >上架</font>
     </button>
   {elseif $value.state eq '1'}
    <button class='sxj' value='2' id="{$value.store_id}" >
        <input type="hidden" value="{$value.store_id}"/>
        <font color='blue' class="{$value.store_id}" >下架</font>
    </button>
   {/if}
   </td>
  </tr>
  {else}
  {/if}
  {/foreach}
</table>
<div  style="margin-left:700px;margin-top:10px;">
&nbsp;&nbsp;{$indexpage}&nbsp;&nbsp;&nbsp;{$lastpage}&nbsp;&nbsp;{$nextpage}&nbsp;&nbsp;{$endpage} &nbsp;&nbsp;
当前第 {$page} 页 &nbsp;&nbsp;
共 &nbsp;{$page_all_num} &nbsp;页
</div>
  </body>
</html>
